# Generated by Django 4.2.2 on 2023-06-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
